//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _86ME_ver2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_86ME_ver2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add2 {
            get {
                object obj = ResourceManager.GetObject("add2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_arrow {
            get {
                object obj = ResourceManager.GetObject("down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Firmata is a generic protocol for communicating with microcontrollers
        /// * from software on a host computer. It is intended to work with
        /// * any host computer software package.
        /// *
        /// * To download a host software package, please clink on the following link
        /// * to open the download page in your default browser.ser
        /// *
        /// * http://firmata.org/wiki/Download
        /// */
        ///
        ////*
        /// Copyright (C) 2006-2008 Hans-Christoph Steiner.  All rights reserved.
        /// Copyright (C) 2010-2011 Paul Stoffregen.  All rights reserved.
        /// Copyright (C)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirmataPlus {
            get {
                return ResourceManager.GetString("FirmataPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hand_close {
            get {
                object obj = ResourceManager.GetObject("hand_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hand_open {
            get {
                object obj = ResourceManager.GetObject("hand_open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap load_frame {
            get {
                object obj = ResourceManager.GetObject("load_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap modify {
            get {
                object obj = ResourceManager.GetObject("modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p {
            get {
                object obj = ResourceManager.GetObject("p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s {
            get {
                object obj = ResourceManager.GetObject("s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;extensionName&quot;: &quot;s2r_fm - Scratch to Robot&quot;,
        ///    &quot;extensionPort&quot;: 50209,
        ///    &quot;url&quot;: &quot;https://github.com/MrYsLab/PyMata&quot;,
        ///    &quot;blockSpecs&quot;: [
        ///        // separate
        ///        [
        ///            &quot; &quot;,
        ///            &quot;%m.pin_state : Digital Pin %m.digital_pins for %m.digital_pin_mode&quot;,
        ///            &quot;digital_pin_mode&quot;,
        ///            &quot;Enable&quot;,
        ///            &quot;PIN&quot;,
        ///            &quot;INPUT&quot;
        ///        ],
        ///        // separate
        ///        [
        ///            &quot; &quot;,
        ///            &quot;%m.pin_state : Analog Pin (A) %n for Input&quot;,
        ///            &quot;analog_pin_mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s2r_fm {
            get {
                return ResourceManager.GetString("s2r_fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_frame {
            get {
                object obj = ResourceManager.GetObject("save_frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sb2 {
            get {
                object obj = ResourceManager.GetObject("sb2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;objName&quot;: &quot;Stage&quot;,
        ///	&quot;sounds&quot;: [{
        ///			&quot;soundName&quot;: &quot;pop&quot;,
        ///			&quot;soundID&quot;: 1,
        ///			&quot;md5&quot;: &quot;83a9787d4cb6f3b7632b4ddfebf74367.wav&quot;,
        ///			&quot;sampleCount&quot;: 258,
        ///			&quot;rate&quot;: 11025,
        ///			&quot;format&quot;: &quot;&quot;
        ///		}],
        ///	&quot;costumes&quot;: [{
        ///			&quot;costumeName&quot;: &quot;backdrop1&quot;,
        ///			&quot;baseLayerID&quot;: 3,
        ///			&quot;baseLayerMD5&quot;: &quot;739b5e2a2435f6e1ec2993791b423146.png&quot;,
        ///			&quot;bitmapResolution&quot;: 1,
        ///			&quot;rotationCenterX&quot;: 240,
        ///			&quot;rotationCenterY&quot;: 180
        ///		}],
        ///	&quot;currentCostumeIndex&quot;: 0,
        ///	&quot;penLayerMD5&quot;: &quot;5c81a336fab8be57adc039a8a2b33ca9.png&quot;,
        ///	&quot;penLayerID&quot;: 0,
        ///	&quot;tempoBP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sb2ProjectJson {
            get {
                return ResourceManager.GetString("sb2ProjectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # -*- coding: utf-8 -*-
        ///
        ///&quot;&quot;&quot;
        ///Created on Wed Nov  25 13:17:15 2013
        ///
        ///@author: Alan Yorinks
        ///Copyright (c) 2013-14 Alan Yorinks All right reserved.
        ///
        ///@co-author: Sjoerd Dirk Meijer, fromScratchEd.nl (language support)
        ///
        ///This program is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU Lesser General Public
        ///License as published by the Free Software Foundation; either
        ///version 2.1 of the License, or (at your option) any later version.
        ///
        ///This library is distributed in the hope that it  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scratch_command_handlers {
            get {
                return ResourceManager.GetString("scratch_command_handlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_arrow {
            get {
                object obj = ResourceManager.GetObject("up_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
